name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # প্রতিদিন midnight এ run হবে
  workflow_dispatch:  # manually ও run করা যাবে

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests Pillow

      - name: Generate Stats Images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Putin57
        run: python generate_stats.py

      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add assets/
          git diff --cached --quiet || git commit -m "Update GitHub Stats"
          git push
